# Utiliser l'image de base officielle openjdk
FROM openjdk:13

# Copier les fichiers statiques dans le dossier de contenu de openjdk
COPY ../API_Membre /usr/src/app

WORKDIR /usr/src/app

# Exposer le port 8080
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "./build/libs/api_membre-0.0.1-SNAPSHOT.jar"]